import type { Category, Order, Product } from "@/lib/types";

export const categories: Category[] = [
  "Lawn",
  "Chiffon",
  "Khaddar",
  "Silk",
  "Cotton",
];

export const brand = {
  name: "ayeshaswear",
  tagline: "Your fit. Your stitch",
  logo: "/brand/logo-mark.png",
  /** Full lockup artwork: the name curved above the mark, transparent bg */
  lockup: "/brand/logo-lockup.png",
};

export const seedProducts: Product[] = [
  {
    id: "p-001",
    slug: "ivory-garden-lawn",
    name: "Ivory Garden Lawn",
    description:
      "A three-piece unstitched lawn with a soft floral print on the shirt, a dyed trouser, and a printed voile dupatta. Light enough for daily wear.",
    price: 5890,
    category: "Lawn",
    image: "/products/suit-ivory-garden.png",
    fabric: "/products/fabric-ivory-blue.png",
    color: "Ivory",
    stock: 24,
    featured: true,
    details: [
      "3-piece unstitched",
      "Shirt 2.5 m · Trouser 2.5 m · Dupatta 2.5 m",
      "Digital print lawn",
      "Women only",
    ],
  },
  {
    id: "p-002",
    slug: "dust-rose-khaddar",
    name: "Dust Rose Khaddar",
    description:
      "Winter khaddar in a muted rose. Yarn-dyed texture on the shirt, a matching trouser, and a jacquard border dupatta.",
    price: 6490,
    category: "Khaddar",
    image: "/products/suit-dust-rose.png",
    fabric: "/products/fabric-rose.png",
    color: "Dust rose",
    stock: 18,
    featured: true,
    details: [
      "3-piece unstitched",
      "Shirt 3 m · Trouser 2.5 m · Dupatta 2.5 m",
      "Pure khaddar",
      "Women only",
    ],
  },
  {
    id: "p-003",
    slug: "midnight-chiffon",
    name: "Midnight Chiffon",
    description:
      "An evening chiffon suit. Embroidered shirt panel, silk trouser, and a sequin-scatter dupatta in deep slate.",
    price: 14900,
    category: "Chiffon",
    image: "/products/suit-midnight.png",
    fabric: "/products/fabric-midnight.png",
    color: "Midnight",
    stock: 10,
    featured: true,
    details: [
      "3-piece unstitched",
      "Embroidered chiffon shirt",
      "Silk trouser · Chiffon dupatta",
      "Women only",
    ],
  },
  {
    id: "p-004",
    slug: "sand-cotton",
    name: "Sand Cotton",
    description:
      "A clean cotton set in warm sand. Solid shirt and trouser with a contrast border on the dupatta. Made for everyday stitching.",
    price: 3990,
    category: "Cotton",
    image: "/products/suit-sand.png",
    fabric: "/products/fabric-ivory-blue.png",
    color: "Sand",
    stock: 40,
    featured: false,
    details: [
      "3-piece unstitched",
      "Shirt 2.5 m · Trouser 2.25 m · Dupatta 2.25 m",
      "Cambric cotton",
      "Women only",
    ],
  },
  {
    id: "p-005",
    slug: "sage-printed-lawn",
    name: "Sage Printed Lawn",
    description:
      "Botanical print lawn in sage and ash. Shirt front is printed; sleeves and trouser stay quieter so the stitch can lead.",
    price: 5290,
    category: "Lawn",
    image: "/products/suit-sage.png",
    fabric: "/products/fabric-sage.png",
    color: "Sage",
    stock: 30,
    featured: false,
    details: [
      "3-piece unstitched",
      "Printed lawn shirt",
      "Dyed trouser · Printed dupatta",
      "Women only",
    ],
  },
  {
    id: "p-006",
    slug: "slate-silk",
    name: "Slate Silk",
    description:
      "Raw silk in a cool slate. Minimal embroidery on the daman, a straight trouser, and a tissue dupatta.",
    price: 18900,
    category: "Silk",
    image: "/products/suit-slate.png",
    fabric: "/products/fabric-midnight.png",
    color: "Slate",
    stock: 8,
    featured: true,
    details: [
      "3-piece unstitched",
      "Raw silk shirt and trouser",
      "Tissue dupatta",
      "Women only",
    ],
  },
  {
    id: "p-007",
    slug: "pearl-chiffon",
    name: "Pearl Chiffon",
    description:
      "Pale chiffon with tone-on-tone work. Soft enough for a daytime function, still quiet in the hand.",
    price: 12900,
    category: "Chiffon",
    image: "/products/suit-pearl.png",
    fabric: "/products/fabric-ivory-blue.png",
    color: "Pearl",
    stock: 12,
    featured: false,
    details: [
      "3-piece unstitched",
      "Embroidered chiffon",
      "Silk inner · Chiffon dupatta",
      "Women only",
    ],
  },
  {
    id: "p-008",
    slug: "charcoal-khaddar",
    name: "Charcoal Khaddar",
    description:
      "A dense winter khaddar in charcoal. Self checks on the shirt, a solid trouser, and a wool-blend shawl dupatta.",
    price: 7290,
    category: "Khaddar",
    image: "/products/suit-charcoal.png",
    fabric: "/products/fabric-charcoal.png",
    color: "Charcoal",
    stock: 16,
    featured: false,
    details: [
      "3-piece unstitched",
      "Shirt 3 m · Trouser 2.5 m · Shawl 2.5 m",
      "Heavy khaddar",
      "Women only",
    ],
  },
  {
    id: "p-009",
    slug: "blush-lawn",
    name: "Blush Lawn",
    description:
      "Light lawn in blush with a scattered motif. Meant to be stitched as a straight kameez or a slightly flared cut.",
    price: 4690,
    category: "Lawn",
    image: "/products/suit-blush.png",
    fabric: "/products/fabric-blush.png",
    color: "Blush",
    stock: 28,
    featured: false,
    details: [
      "3-piece unstitched",
      "Lawn shirt and trouser",
      "Voile dupatta",
      "Women only",
    ],
  },
  {
    id: "p-010",
    slug: "graphite-cotton",
    name: "Graphite Cotton",
    description:
      "A darker cotton for daily wear. Fine stripe on the shirt, matching trouser, and a plain dyed dupatta.",
    price: 4290,
    category: "Cotton",
    image: "/products/suit-graphite.png",
    fabric: "/products/fabric-charcoal.png",
    color: "Graphite",
    stock: 22,
    featured: false,
    details: [
      "3-piece unstitched",
      "Cambric cotton",
      "Shirt 2.5 m · Trouser 2.5 m · Dupatta 2.25 m",
      "Women only",
    ],
  },
  {
    id: "p-011",
    slug: "fog-silk",
    name: "Fog Silk",
    description:
      "Muted silk with a faint weave. A quieter formal set — shirt, trouser, and a lightly crushed dupatta.",
    price: 16900,
    category: "Silk",
    image: "/products/suit-fog.png",
    fabric: "/products/fabric-ivory-blue.png",
    color: "Fog",
    stock: 9,
    featured: false,
    details: [
      "3-piece unstitched",
      "Pure silk",
      "Crushed dupatta",
      "Women only",
    ],
  },
  {
    id: "p-012",
    slug: "ash-printed-lawn",
    name: "Ash Printed Lawn",
    description:
      "Monochrome print lawn. The shirt carries the motif; trouser and dupatta stay ash so the stitch stays clean.",
    price: 5490,
    category: "Lawn",
    image: "/products/suit-ash.png",
    fabric: "/products/fabric-ivory-blue.png",
    color: "Ash",
    stock: 20,
    featured: false,
    details: [
      "3-piece unstitched",
      "Digital print",
      "Shirt 2.75 m · Trouser 2.5 m · Dupatta 2.5 m",
      "Women only",
    ],
  },
];

export const seedOrders: Order[] = [
  {
    id: "ORD-1048",
    trackingId: "SW-1048-A1B2",
    items: [
      {
        productId: "p-001",
        name: "Ivory Garden Lawn",
        price: 5890,
        quantity: 1,
      },
      { productId: "p-005", name: "Sage Printed Lawn", price: 5290, quantity: 1 },
    ],
    customer: {
      name: "Ayesha Khan",
      email: "ayesha.khan@email.com",
      phone: "03001234567",
      address: "12-B DHA Phase 6",
      city: "Lahore",
      country: "Pakistan",
    },
    total: 11180,
    shipping: 0,
    status: "Paid",
    createdAt: "2026-09-04T14:20:00.000Z",
  },
  {
    id: "ORD-1047",
    trackingId: "SW-1047-C3D4",
    items: [
      { productId: "p-003", name: "Midnight Chiffon", price: 14900, quantity: 1 },
    ],
    customer: {
      name: "Fatima Rizvi",
      email: "fatima.rizvi@email.com",
      phone: "03219876543",
      address: "44 Clifton Block 5",
      city: "Karachi",
      country: "Pakistan",
    },
    total: 14900,
    shipping: 0,
    status: "Shipped",
    createdAt: "2026-09-03T09:12:00.000Z",
  },
  {
    id: "ORD-1046",
    trackingId: "SW-1046-E5F6",
    items: [
      { productId: "p-006", name: "Slate Silk", price: 18900, quantity: 1 },
    ],
    customer: {
      name: "Hira Malik",
      email: "hira.malik@email.com",
      phone: "03335551212",
      address: "8 F-7 Markaz",
      city: "Islamabad",
      country: "Pakistan",
    },
    total: 18900,
    shipping: 0,
    status: "Delivered",
    createdAt: "2026-09-01T16:40:00.000Z",
  },
  {
    id: "ORD-1045",
    trackingId: "SW-1045-G7H8",
    items: [
      { productId: "p-002", name: "Dust Rose Khaddar", price: 6490, quantity: 2 },
    ],
    customer: {
      name: "Sana Qureshi",
      email: "sana.qureshi@email.com",
      phone: "03445550011",
      address: "19 Gulberg III",
      city: "Lahore",
      country: "Pakistan",
    },
    total: 12980,
    shipping: 0,
    status: "Pending",
    createdAt: "2026-08-30T11:05:00.000Z",
  },
];
